### PR TITLE
Fixed missing doc build lib/ files & deps

### LINKED ISSUE #37: Doc build is missing lib/* files & build deps
The doc build is missing files in the template `/lib` directory and also does not include the build tools as dev deps of the package.

### PR DESCRIPTION
**Pull request by glenselle**
Resolves #37 

Also fixes a `className` assignment that was wiping a class in the navbar thus causing the mobile hamburger menu to disappear only when going to ol-kit.com without any file path after the domain.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,7 +1,7 @@
 coverage/
 dist/
 .jest/
-lib/
+/lib
```
Comment (glenselle) [inline .gitignore:4]: this was preventing the lib dir inside of the template from being included

File: docs/scripts/app.js [hunk 2]
```diff
@@ -18,7 +18,7 @@ for (var i = 0; i < links.length; i++) {
     var linkFile = linkParts[linkParts.length - 1]
 
     if (urlFile === linkFile) {
-        el.className = 'active'
+        el.className += 'active'
```
Comment (glenselle) [inline docs/scripts/app.js:21]: this fixes the mobile navbar which would never show on ol-kit.com b/c it wiped all other classes
